import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Board } from "../components/Board/Board";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Board />
      </main>
    </div>
  );
}
