import Head from "next/head";

import { Board } from "../components/Board/Board";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-2xl ml-2 py-4">
          Kanban board using GraphQL subscriptions
        </h1>
        <Board />
      </main>
    </div>
  );
}
